---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcurl
  name: grpcurl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcurl
  template:
    metadata:
      labels:
        app: grpcurl
    spec:
      HostNetwork: true
      containers:
      - image: localhost/grpcurl:latest
        name: grpcurl
        resources: 
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
