name: Blank Issue
description: Open a blank issue with no predefined structure
title: "[Blank Issue] ..."
labels: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe your issue
    validations:
      required: true

